email:
  noreply: noreply@halisaa.com

rollbar:
  access_token: 0a38efefefff478b8df0062c5e66e616
smtp:
  mandrill:
    address: 'smtp.mandrillapp.com'
    port: 587
    enable_starttls_auto: true
    user_name: 'isogmail@gmail.com'
    password: 'B9GaJCJ7tJ0b0_ZlQE7czw'
    authentication: 'plain'
