smtp:
  mandrill:
    address: 'smtp.mandrillapp.com'
    port: 587
    enable_starttls_auto: true
    user_name: 'email@email.com'
    password: 'password'
    authentication: 'plain'

AWS:
  S3:
    bucket: projectname-production
    access_key_id: XXXXXXXXXXXXXXXX
    secret_access_key: YYYYYYYYYYYYYYYYYY
    aws_url: http://projectname-production.s3.amazonaws.com/
    aws_raw_url: projectname-production.s3.amazonaws.com
    end_point: s3-eu-west-1.amazonaws.com